#!/bin/bash
echo '##################################################################
#           ENTER THE FOLLOWING ON THE CLIENT COMPUTER           #
##################################################################
****************(Will need root/sudo to do these!)****************
 # ip addr flush dev [INTERFACE]
 # ip addr add 192.168.11.2/24 dev [INTERFACE]
 # ip link set up dev [INTERFACE]
 # ip route add default via 192.168.11.1 dev [INTERFACE]
##################################################################


##################################################################
#            TO GAIN PROXY ACCESS ON REMOTE COMPUTER             #
##################################################################
***********************Run this locally:**************************
 $ ssh -vvv -N -R 10007:localhost:10007 [-p PORT] user@host

*************************Run on remote:***************************
 $ export all_proxy="socks5://127.0.0.1:10007"
##################################################################'
